# Generated by Django 3.1.7 on 2021-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=10),
        ),
    ]
